/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/rI7hfsusqUw
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Rethink_Sans } from 'next/font/google'
import { DM_Sans } from 'next/font/google'

rethink_sans({
  subsets: ['latin'],
  display: 'swap',
})

dm_sans({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { TextGenerateEffect } from "../ui/text-generate-effect.jsx";

export default function landing() {

  const words = `Elevate Your Tech Blogging Presence`
  return (
    (<div className="flex flex-col items-center justify-center min-h-screen bg-white">
      <div className="max-w-3xl px-4 md:px-0 text-center -mt-16">
        <h1 className="text-5xl font-bold tracking-tight text-gray-900 sm:text-6xl">
            <TextGenerateEffect words={words}/>
        </h1>
        <p className="mt-6 text-xl text-gray-500">
        Where Ideas Merge, Stories Evolve
        </p>
      </div>
    </div>
    
    )
  );
}
