/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/lbcgvUPZP5P
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Card, CardContent, CardFooter } from "@/components/ui/card"
import { Avatar, AvatarFallback } from "@/components/ui/avatar"
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"

export function profile() {
  return (
    (<Card className="w-full max-w-4xl">
      <div className="flex items-center gap-6 p-6 border-b">
        <Avatar className="h-16 w-16">
          <AvatarFallback>USER</AvatarFallback>
        </Avatar>
        <div className="grid gap-1">
          <div className="text-2xl font-bold">Jared Palmer</div>
          <div className="text-sm text-muted-foreground">@jaredpalmer</div>
        </div>
      </div>
      <CardContent className="p-6 space-y-6">
        <div className="grid grid-cols-2 gap-6">
          <div className="space-y-2">
            <Label htmlFor="username">Change Username</Label>
            <Input id="username" defaultValue="Jared Palmer" />
          </div>
          <div className="space-y-2">
            <Label htmlFor="email">Change Email</Label>
            <Input id="email" type="email" defaultValue="jared@example.com" />
          </div>
        </div>
        <div className="space-y-2">
          <Label htmlFor="password">Change Password</Label>
          <Input id="password" type="password" defaultValue="jared@example.com" />
        </div>
      </CardContent>
      <CardFooter className="flex justify-end p-6">
        <Button>Save Changes</Button>
      </CardFooter>
    </Card>)
  );
}
